"""
create_pr.py - 自动创建 GitHub Pull Request

读取 review_result.json，构建 PR 描述，通过 GitHub API 创建 PR。
在容器内运行，所有环境变量已由 entrypoint.sh 设置。
"""

import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path


def create_pr():
    # 从环境变量读取配置
    task_id = os.environ.get("TASK_ID", "unknown")
    task_title = os.environ.get("TASK_TITLE", "Unknown Task")
    repo_url = os.environ.get("REPO_URL", "")
    branch_name = os.environ.get("BRANCH_NAME", f"task/{task_id}")
    github_token = os.environ.get("GIT_TOKEN") or os.environ.get("GITHUB_TOKEN", "")

    if not github_token:
        print("[create_pr] GIT_TOKEN not set, skipping PR creation", file=sys.stderr)
        return

    # 提取 owner/repo
    owner_repo = extract_owner_repo(repo_url)
    if not owner_repo:
        print(f"[create_pr] Cannot extract owner/repo from: {repo_url}", file=sys.stderr)
        return

    # 读取 review 结果
    review_result = {}
    review_path = Path("/workspace/review_result.json")
    if review_path.exists():
        try:
            review_result = json.loads(review_path.read_text())
        except json.JSONDecodeError:
            pass

    verdict = review_result.get("verdict", "unknown")
    score = review_result.get("score", 0)
    summary = review_result.get("summary", "")
    issues = review_result.get("issues", [])
    recommendation = review_result.get("recommendation", "approve")

    # 构建 PR 正文
    verdict_emoji = "✅" if verdict == "pass" else "❌"
    issue_lines = "\n".join(
        f"- **[{i['severity'].upper()}]** `{i.get('file', '?')}:{i.get('line', '?')}` "
        f"{i['description']} → {i.get('suggestion', '')}"
        for i in issues[:10]  # 最多显示10条
    ) or "No issues found."

    pr_body = f"""## Task: {task_title}

**Task ID**: `{task_id}`
**Branch**: `{branch_name}`

---

## Code Review Summary

{verdict_emoji} **Verdict**: `{verdict}` | **Score**: {score}/100

{summary}

### Issues Found

{issue_lines}

### Recommendation

`{recommendation}`

---

*Generated by [Claude Pipeline](https://github.com/anthropics/claude-code) 🤖*
"""

    # 确定 base branch（默认 main，也检查 master）
    base_branch = detect_default_branch(owner_repo, github_token) or "main"

    # 调用 GitHub API 创建 PR
    api_url = f"https://api.github.com/repos/{owner_repo}/pulls"
    payload = {
        "title": f"feat(task-{task_id}): {task_title}",
        "head": branch_name,
        "base": base_branch,
        "body": pr_body,
        "draft": verdict != "pass",  # Review 失败时创建草稿 PR
    }

    headers = {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": f"token {github_token}",
        "Content-Type": "application/json",
        "User-Agent": "claude-pipeline/1.0",
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(api_url, data=data, headers=headers, method="POST")

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode())
            pr_url = result.get("html_url", "")
            print(f"[create_pr] PR created: {pr_url}")
            # 写入文件供 orchestrator 读取
            Path("/workspace/pr_url.txt").write_text(pr_url)
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()
        # 如果 PR 已存在（422），打印警告但不失败
        if e.code == 422 and "already exists" in error_body:
            print(f"[create_pr] PR already exists for branch {branch_name}", file=sys.stderr)
        else:
            print(f"[create_pr] GitHub API error {e.code}: {error_body}", file=sys.stderr)
    except Exception as e:
        print(f"[create_pr] Error: {e}", file=sys.stderr)


def extract_owner_repo(url: str) -> str:
    """从 GitHub URL 中提取 owner/repo。"""
    url = url.rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]
    # 移除认证信息
    if "@" in url:
        url = "https://github.com/" + url.split("github.com/")[-1]
    parts = url.split("github.com/")
    return parts[1] if len(parts) == 2 else ""


def detect_default_branch(owner_repo: str, token: str) -> str:
    """通过 GitHub API 获取仓库默认分支。"""
    api_url = f"https://api.github.com/repos/{owner_repo}"
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": f"token {token}",
        "User-Agent": "claude-pipeline/1.0",
    }
    try:
        req = urllib.request.Request(api_url, headers=headers)
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            return data.get("default_branch", "main")
    except Exception:
        return "main"


if __name__ == "__main__":
    create_pr()
